script: |
  cd /home/ubuntu/aryansinghbattan-del
  git pull origin main

  sudo docker stop myportfolio || true
  sudo docker rm myportfolio || true

  sudo docker build -t aryanportfolio .

  sudo docker run -d \
    --name myportfolio \
    -p 80:80 \
    aryanportfolio